# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 09:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('FB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(help_text='Required. 30 characters or fewer. Letters, numbers and @/./+/-/_ characters', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[ \\w.@+-]+$', 32), 'Enter a valid username.', 'invalid')], verbose_name='username'),
        ),
    ]
